import { Game } from "../game/Game";
import { rewardCards } from "../data/cards";

export type NuzlockeRule =
  | "permadeath" | "noHealing" | "noRecruit" | "limitedRecruit" | "noBurnoutRecovery" | "noStressRecovery" | "noReplacement" | "firstPick"
  | "noSwitch" | "noBackpack" | "oneEquipment" | "noCardRemoval" | "deckLock" | "noRest" | "randomPath" | "eliteMandatory"
  | "noCode" | "noDebug" | "noDefense" | "noBattleSwitch" | "twoEnergy" | "smallHand" | "oneTool" | "noDuplicates" | "noCoffee" | "noAI" | "noGit"
  | "battleCardLock";
type NuzGame = Game & { nuzlockeActive:boolean; nuzlockeGraveyard:string[]; nuzlockeRules:NuzlockeRule[]; nuzlockeRecruitCount:number; nuzlockeFirstPickId?:string|null };
const labels:Record<NuzlockeRule,string>={permadeath:"PERMADEATH",noHealing:"NIENTE GUARIGIONE",noRecruit:"TEAM BLOCCATO",limitedRecruit:"UN SOLO RECLUTAMENTO",noBurnoutRecovery:"BURNOUT PERMANENTE",noStressRecovery:"NIENTE RECUPERO STRESS",noReplacement:"NO SOSTITUZIONI",firstPick:"FIRST PICK",noSwitch:"NO CAMBIO",noBackpack:"NO ZAINO",oneEquipment:"UN SOLO EQUIPMENT",noCardRemoval:"NO RIMOZIONE CARTE",deckLock:"DECK LOCK",noRest:"NO PAUSA",randomPath:"PERCORSO CASUALE",eliteMandatory:"ELITE OBBLIGATORIA",noCode:"NO CODICE",noDebug:"NO DEBUG",noDefense:"NO DIFESA",noBattleSwitch:"CAMBIO VIETATO IN COMBATTIMENTO",twoEnergy:"2 ENERGIA",smallHand:"MANO DA 2",oneTool:"UN SOLO TOOL",noDuplicates:"NO DOPPIONI",noCoffee:"NO CAFFÈ",noAI:"NO AI",noGit:"NO GIT",battleCardLock:"MONOUSO IN BATTAGLIA"};
const groups:[string,NuzlockeRule[]][]=[
 ["SOPRAVVIVENZA",["permadeath","noHealing","noBurnoutRecovery","noStressRecovery","noRest"]],
 ["TEAM",["noRecruit","limitedRecruit","noReplacement","firstPick","noSwitch","noBattleSwitch"]],
 ["RISORSE",["noBackpack","oneEquipment","noCardRemoval","deckLock","noDuplicates"]],
 ["MAPPA",["randomPath","eliteMandatory"]],
 ["COMBATTIMENTO",["noCode","noDebug","noDefense","twoEnergy","smallHand","oneTool","battleCardLock"]],
 ["CAOS DEVLIKE",["noCoffee","noAI","noGit"]]
];
const descriptions:Record<NuzlockeRule,string>={permadeath:"Un Developer a 0 HP viene perso definitivamente.",noHealing:"La PAUSA non cura HP e le carte che curano HP sono vietate.",noRecruit:"Dopo la scelta iniziale non puoi reclutare Developer.",limitedRecruit:"Puoi reclutare o sostituire un solo Developer per tutta la run.",noBurnoutRecovery:"Un Developer che raggiunge BURNOUT mantiene lo Stress al proprio limite personale durante la PAUSA.",noStressRecovery:"La PAUSA non riduce lo Stress e le carte che rimuovono Stress sono vietate.",noReplacement:"Con 3 Developer non puoi sostituirne nessuno.",firstPick:"Il Developer scelto all'inizio non può essere sostituito.",noSwitch:"L'azione CAMBIO non è disponibile.",noBackpack:"Gli oggetti non possono essere conservati nello ZAINO.",oneEquipment:"Ogni Developer ha un solo slot Equipment.",noCardRemoval:"Le carte non possono essere rimosse dal mazzo.",deckLock:"Il mazzo non può essere modificato durante la run, salvo le normali aggiunte di ricompense.",noRest:"I nodi PAUSA sono vietati.",randomPath:"La scelta del nodo viene effettuata casualmente tra quelli disponibili.",eliteMandatory:"Se è disponibile un ELITE, devi affrontarlo.",noCode:"L'azione CODICE è vietata.",noDebug:"L'azione DEBUG è vietata.",noDefense:"L'azione DIFESA è vietata.",noBattleSwitch:"Non puoi cambiare Developer durante un combattimento.",twoEnergy:"Ogni turno hai solo 2 Energia.",smallHand:"Peschi 2 carte invece di 3.",oneTool:"Puoi giocare un solo Tool per turno.",noDuplicates:"Non puoi aggiungere una carta già presente nel mazzo.",noCoffee:"Le carte con CAFFÈ nel nome non possono essere utilizzate.",noAI:"Le carte AI/CHATGPT non possono essere utilizzate.",noGit:"Le carte GIT non possono essere utilizzate.",battleCardLock:"Una carta giocata non può essere riutilizzata nello stesso combattimento. Ogni nuovo combattimento ripristina tutte le carte.",};
const allRules=groups.flatMap(([,rules])=>rules);
const incompatible:NuzlockeRule[][]=[
 ["noRecruit","limitedRecruit"],
 ["noRecruit","noReplacement"],
 ["noRecruit","firstPick"],
 ["noReplacement","firstPick"],
 ["noSwitch","noBattleSwitch"],
 ["noRest","noHealing"],
 ["noRest","noStressRecovery"],
 ["noRest","noBurnoutRecovery"],
 ["noStressRecovery","noBurnoutRecovery"],
 ["deckLock","noCardRemoval"],
];
function randomRules(count=7):NuzlockeRule[]{const target=Math.max(2,Math.min(count,allRules.length));const result:NuzlockeRule[]=["permadeath"];let pool=[...allRules.filter(r=>r!=="permadeath")].sort(()=>Math.random()-.5);while(result.length<target&&pool.length){const rule=pool.shift()!;if(incompatible.some(pair=>pair.includes(rule)&&pair.some(other=>other!==rule&&result.includes(other))))continue;result.push(rule);}return result;}
function selectedRules(){return [...document.querySelectorAll<HTMLInputElement>("[data-nuz-rule]:checked")].map(x=>x.dataset.nuzRule as NuzlockeRule);}
function syncRuleConflicts(){const selected=selectedRules();document.querySelectorAll<HTMLInputElement>("[data-nuz-rule]").forEach(input=>{const rule=input.dataset.nuzRule as NuzlockeRule;const blocked=!input.checked&&incompatible.some(pair=>pair.includes(rule)&&pair.some(other=>other!==rule&&selected.includes(other)));input.disabled=blocked;const option=input.closest<HTMLElement>(".nuzlocke-option");option?.classList.toggle("disabled",blocked);option?.setAttribute("aria-disabled",String(blocked));});}
function markup(){return \`<div class="feature-overlay" data-nuzlocke-overlay><div class="feature-window nuzlocke-window nuzlocke-redesign"><header class="nuzlocke-header"><div class="nuzlocke-header-copy"><span class="nuzlocke-kicker">SPECIAL MODE // CHALLENGE CONFIG</span><h2>NUZLOCKE</h2><p>Costruisci la tua run scegliendo quali regole applicare. <b>PERMADEATH</b> è sempre attivo.</p></div><button type="button" class="feature-close nuzlocke-close" data-nuz-close>CHIUDI ×</button></header><div class="nuzlocke-toolbar"><div class="nuzlocke-random-copy"><span class="nuzlocke-tool-label">RUN RAPIDA</span><b>Genera una configurazione casuale</b><small>Le combinazioni incompatibili vengono escluse automaticamente.</small></div><div class="nuzlocke-random-controls"><label><span>REGOLE</span><select data-nuz-random-count><option value="4">4</option><option value="5">5</option><option value="7" selected>7</option><option value="9">9</option><option value="12">12</option></select></label><button type="button" class="secondary nuzlocke-random-button" data-nuz-random>RANDOM + START</button></div></div><div class="nuzlocke-body"><aside class="nuzlocke-sidebar"><div class="nuzlocke-sidebar-head"><span>MODIFICATORI</span><strong data-nuz-count>01</strong></div><p>Attiva o disattiva i limiti. Le regole incompatibili vengono bloccate automaticamente.</p><div class="nuzlocke-legend"><i></i><span>ATTIVA</span><em></em><span>BLOCCATA</span></div></aside><main class="nuzlocke-groups">\${groups.map(([name,rules])=>\`<section class="nuzlocke-group"><div class="nuzlocke-group-head"><span>\${name}</span><i></i></div><div class="nuzlocke-rule-grid">\${rules.map(rule=>\`<label class="nuzlocke-option \${rule==="permadeath"?"selected":""}"><input type="checkbox" data-nuz-rule="\${rule}" \${rule==="permadeath"?"checked":""}><span><b>\${labels[rule]}</b><small>\${descriptions[rule]}</small></span></label>\`).join("")}</div></section>\`).join("")}</main></div><footer class="nuzlocke-footer"><div class="nuzlocke-selection"><span>CONFIGURAZIONE ATTUALE</span><strong data-nuz-summary>1 REGOLA · PERMADEATH</strong></div><button type="button" class="primary nuzlocke-start" data-nuz-start>INIZIA NUZLOCKE <span>→</span></button></footer></div></div>\`;}
function summary(){const rules=selectedRules();const el=document.querySelector<HTMLElement>("[data-nuz-summary]");if(el)el.textContent=rules.length?rules.length+" REGOLE · "+rules.map(r=>labels[r]).join(" · "):"NESSUNA REGOLA";const count=document.querySelector<HTMLElement>("[data-nuz-count]");if(count)count.textContent=String(rules.length).padStart(2,"0");}
function applyRandomSelection(count:number){const rules=randomRules(count);document.querySelectorAll<HTMLInputElement>("[data-nuz-rule]").forEach(input=>{input.checked=rules.includes(input.dataset.nuzRule as NuzlockeRule);input.closest(".nuzlocke-option")?.classList.toggle("selected",input.checked);});syncRuleConflicts();summary();return rules;}
export function setupNuzlocke(game:NuzGame){
 game.nuzlockeActive??=false;game.nuzlockeGraveyard??=[];game.nuzlockeRules??=["permadeath"];game.nuzlockeRecruitCount??=0;game.nuzlockeFirstPickId??=null;

 const originalConfirmStarting=game.confirmStartingDeveloper.bind(game);game.confirmStartingDeveloper=()=>{const id=game.selectedStartingId;originalConfirmStarting();if(game.nuzlockeActive&&game.nuzlockeRules.includes("firstPick"))game.nuzlockeFirstPickId=id??null;};
 const originalStart=game.start.bind(game);game.start=()=>{originalStart();game.nuzlockeGraveyard=[];game.nuzlockeRecruitCount=0;game.nuzlockeFirstPickId=null;};
 const originalSelect=game.selectMapNode.bind(game);game.selectMapNode=(id:string)=>{if(!game.nuzlockeActive){originalSelect(id);return;}const available=game.availableMapNodes;const recruitBlocked=(node:typeof available[number])=>node.type==="recruit"&&(game.nuzlockeRules.includes("noRecruit")||(game.nuzlockeRules.includes("limitedRecruit")&&game.nuzlockeRecruitCount>=1));const restBlocked=(node:typeof available[number])=>node.type==="rest"&&game.nuzlockeRules.includes("noRest");const selectable=available.filter(node=>!recruitBlocked(node)&&!restBlocked(node));let target=available.find(n=>n.id===id);if(recruitBlocked(target!)||restBlocked(target!)){if(target?.type==="rest"&&target.id==="rest-final"){target.visited=true;game.currentMapNodeId=target.id;game.currentNode=target.row;const boss=game.mapNodes.find(n=>n.id==="boss-final");if(boss){boss.visited=false;game.message="NUZLOCKE: PAUSA FINALE SALTATA. LA DEADLINE È DAVANTI A TE.";originalSelect(boss.id);}return;}game.message=target?.type==="rest"?"NUZLOCKE: PAUSA VIETATA.":game.nuzlockeRules.includes("noRecruit")?"NUZLOCKE: TEAM BLOCCATO.":"NUZLOCKE: RECLUTAMENTO GIÀ UTILIZZATO.";return;}if(game.nuzlockeRules.includes("randomPath")&&selectable.length){target=selectable[Math.floor(Math.random()*selectable.length)];id=target.id;}if(game.nuzlockeRules.includes("eliteMandatory")){const elite=selectable.find(n=>n.type==="elite");if(elite){target=elite;id=elite.id;}}if(!target||!selectable.some(n=>n.id===target!.id))return;const hp=game.team.map(d=>d.hp),stress=game.team.map(d=>d.stress);originalSelect(id);if(target.type==="rest"){if(game.nuzlockeRules.includes("noHealing"))game.team.forEach((d,i)=>d.hp=hp[i]);if(game.nuzlockeRules.includes("noStressRecovery"))game.team.forEach((d,i)=>d.stress=stress[i]);if(game.nuzlockeRules.includes("noBurnoutRecovery"))game.team.forEach((d,i)=>{if(stress[i]>=d.maxStress)d.stress=d.maxStress;});}};

 const originalRecruit=game.confirmRecruitment.bind(game);game.confirmRecruitment=()=>{if(!game.nuzlockeActive)return originalRecruit();if(game.nuzlockeRules.includes("noRecruit"))return;if(game.nuzlockeRules.includes("limitedRecruit")&&game.nuzlockeRecruitCount>=1)return;if(game.nuzlockeRules.includes("noReplacement")&&game.team.length>=3){game.message="NUZLOCKE: SOSTITUZIONE VIETATA.";return;}if(game.nuzlockeRules.includes("firstPick")&&game.team.length>=3&&game.team[game.recruitTargetIndex??-1]?.id===game.nuzlockeFirstPickId){game.message="NUZLOCKE: IL FIRST PICK NON PUÒ ESSERE SOSTITUITO.";return;}const before=game.team.map(d=>d.id).join("|");originalRecruit();if(before!==game.team.map(d=>d.id).join("|"))game.nuzlockeRecruitCount++;};
 const originalMoveEquipment=game.moveSelectedEquipment.bind(game);game.moveSelectedEquipment=(targetZone:"dev"|"bag",targetDevIndex=-1,targetItemIndex=-1)=>{if(game.nuzlockeActive&&game.nuzlockeRules.includes("noBackpack")&&targetZone==="bag"){game.message="NUZLOCKE: ZAINO VIETATO. L'OGGETTO DEVE RESTARE EQUIPAGGIATO.";return;}if(game.nuzlockeActive&&game.nuzlockeRules.includes("oneEquipment")&&targetZone==="dev"){const target=game.equipmentTeam[targetDevIndex];const targetSlot=target?.items[targetItemIndex];if(target&&target.items.length>=1&&!targetSlot){game.message="NUZLOCKE: UN SOLO EQUIPMENT PER DEVELOPER.";return;}}originalMoveEquipment(targetZone,targetDevIndex,targetItemIndex);}; const originalChooseEvent=game.chooseEvent.bind(game);game.chooseEvent=(index:number)=>{if(!game.nuzlockeActive){originalChooseEvent(index);return;}const hp=game.team.map(d=>d.hp),stress=game.team.map(d=>d.stress),beforeDeck=game.deck.map(card=>card.id),beforeLength=game.deck.length,beforeInventory=game.inventory.length,beforeCollectionLength=game.cardCollection?.length??0;originalChooseEvent(index);if(game.nuzlockeRules.includes("noBackpack")&&game.inventory.length>beforeInventory){game.inventory.splice(beforeInventory);game.message="NUZLOCKE: ZAINO VIETATO. RICOMPENSA OGGETTO RIFIUTATA.";}if(game.nuzlockeRules.includes("noDuplicates")&&game.deck.length>beforeLength){const added=game.deck.slice(beforeLength);for(let i=added.length-1;i>=0;i--){if(beforeDeck.includes(added[i].id))game.deck.splice(beforeLength+i,1);}if(game.deck.length<beforeLength+added.length){const duplicateIds=new Set(added.filter(card=>beforeDeck.includes(card.id)).map(card=>card.id));if(duplicateIds.size&&game.cardCollection){for(let i=game.cardCollection.length-1;i>=beforeCollectionLength;i--)if(duplicateIds.has(game.cardCollection[i].id))game.cardCollection.splice(i,1);}game.message="NUZLOCKE: DOPPIONE RIFIUTATO.";} }if(game.nuzlockeRules.includes("noHealing"))game.team.forEach((d,i)=>{if(d.hp>hp[i])d.hp=hp[i];});if(game.nuzlockeRules.includes("noStressRecovery"))game.team.forEach((d,i)=>{if(d.stress<stress[i])d.stress=stress[i];});if(game.nuzlockeRules.includes("noBurnoutRecovery"))game.team.forEach((d,i)=>{if(stress[i]>=d.maxStress)d.stress=d.maxStress;});};
 const originalChooseBossReward=game.chooseBossReward.bind(game);game.chooseBossReward=(index:number)=>{if(game.nuzlockeActive){const option=game.bossRewardOptions[index];if(game.nuzlockeRules.includes("noBackpack")&&option?.kind==="item"){game.message="NUZLOCKE: ZAINO VIETATO. SCEGLI UN TOOL.";return;}if(game.nuzlockeRules.includes("noDuplicates")&&option?.kind==="tool"&&option.card&&game.deck.some(card=>card.id===option.card!.id)){const tier=Math.min(4,Math.floor((Math.max(1,game.projectNumber)-1)/5)+1);const alternatives=rewardCards.filter(card=>(card.tier??1)===tier&&!game.deck.some(owned=>owned.id===card.id));if(alternatives.length){game.bossRewardOptions[index]={kind:"tool",card:{...alternatives[Math.floor(Math.random()*alternatives.length)]}};game.message="NUZLOCKE: DOPPIONE RIFIUTATO. RICOMPENSA RIGENERATA.";return;}game.message="NUZLOCKE: NESSUNA RICOMPENSA DISPONIBILE SENZA DOPPIONI.";return;}}originalChooseBossReward(index);};
 const originalStore=game.storeItemReward.bind(game);game.storeItemReward=()=>{if(game.nuzlockeActive&&game.nuzlockeRules.includes("noBackpack")){game.message="NUZLOCKE: ZAINO VIETATO. EQUIPAGGIA L'OGGETTO.";return;}originalStore();};
 const originalEquip=game.confirmItemReward.bind(game);game.confirmItemReward=()=>{if(game.nuzlockeActive&&game.nuzlockeRules.includes("oneEquipment")&&game.selectedItemTargetIndex!==null&&game.team[game.selectedItemTargetIndex]?.items.length>=1){game.message="NUZLOCKE: UN SOLO EQUIPMENT PER DEVELOPER.";return;}originalEquip();};
 const originalChooseReward=game.chooseReward.bind(game);game.chooseReward=(index:number)=>{const card=game.reward;if(game.nuzlockeActive&&card&&game.nuzlockeRules.includes("noDuplicates")&&game.deck.some(c=>c.id===card.id)){const tier=Math.min(4,Math.floor((Math.max(1,game.projectNumber)-1)/5)+1+(game.currentMapNode?.type==="elite"?1:0));const tierPool=rewardCards.filter(candidate=>(candidate.tier??1)===tier&&!game.deck.some(owned=>owned.id===candidate.id));const alternatives=tierPool.length?tierPool:rewardCards.filter(candidate=>(candidate.tier??1)<=tier&&!game.deck.some(owned=>owned.id===candidate.id));if(alternatives.length){game.reward={...alternatives[Math.floor(Math.random()*alternatives.length)]};game.message="NUZLOCKE: DOPPIONE RIFIUTATO. RICOMPENSA RIGENERATA.";return;}game.message="NUZLOCKE: NESSUNA RICOMPENSA DISPONIBILE SENZA DOPPIONI.";return;}originalChooseReward(index);};
 const removeCardFromDeck=(index:number)=>{if(index<0||index>=game.deck.length)return false;if(game.nuzlockeActive&&(game.nuzlockeRules.includes("noCardRemoval")||game.nuzlockeRules.includes("deckLock"))){game.message="NUZLOCKE: RIMOZIONE CARTE VIETATA.";return false;}game.deck.splice(index,1);return true;};
 (game as NuzGame & {removeCardFromDeck?:(index:number)=>boolean}).removeCardFromDeck=removeCardFromDeck;
 const originalFinished=game.onCombatFinished.bind(game);game.onCombatFinished=()=>{const active=game.nuzlockeActive;const rules=game.nuzlockeRules??[];const noHealing=active&&rules.includes("noHealing");const noStressRecovery=active&&rules.includes("noStressRecovery");const noBurnoutRecovery=active&&rules.includes("noBurnoutRecovery");const beforeHp=game.team.map(d=>d.hp);const beforeStress=game.team.map(d=>d.stress);const permadeath=active&&rules.includes("permadeath");const lostIds=permadeath?(game.combat?.team.filter(d=>d.hp<=0).map(d=>d.id)??[]):[];originalFinished();if(noHealing)game.team.forEach((d,i)=>d.hp=Math.min(d.maxHp,beforeHp[i]??d.hp));if(noStressRecovery)game.team.forEach((d,i)=>d.stress=Math.max(0,Math.min(d.maxStress,beforeStress[i]??d.stress)));if(noBurnoutRecovery)game.team.forEach((d,i)=>{if((beforeStress[i]??0)>=d.maxStress)d.stress=d.maxStress;});if(!permadeath)return;const lost=game.team.filter(d=>lostIds.includes(d.id));lost.forEach(d=>{if(!game.nuzlockeGraveyard.includes(d.id))game.nuzlockeGraveyard.push(d.id);});if(lostIds.length)game.team=game.team.filter(d=>!lostIds.includes(d.id));if(!game.team.length){game.screen="result";game.message="NUZLOCKE FAILED · TUTTO IL TEAM È ESAUSTO.";}};
 document.addEventListener("click",event=>{const target=event.target as HTMLElement;const overlay=target.closest<HTMLElement>("[data-nuzlocke-overlay]");const open=target.closest<HTMLElement>('[data-feature-open="nuzlocke"]');if(open){event.preventDefault();event.stopImmediatePropagation();document.querySelector("[data-nuzlocke-overlay]")?.remove();document.querySelector<HTMLElement>(".game-shell")?.insertAdjacentHTML("beforeend",markup());syncRuleConflicts();return;}if(target.closest("[data-nuz-close]")){event.preventDefault();event.stopImmediatePropagation();overlay?.remove();return;}if(target.closest("[data-nuz-random]")){event.preventDefault();event.stopImmediatePropagation();const count=Number(document.querySelector<HTMLSelectElement>("[data-nuz-random-count]")?.value??7);game.nuzlockeRules=applyRandomSelection(count);game.nuzlockeActive=true;game.nuzlockeGraveyard=[];game.nuzlockeRecruitCount=0;game.nuzlockeFirstPickId=null;overlay?.remove();game.start();return;}const option=target.closest<HTMLLabelElement>(".nuzlocke-option");if(option){const input=option.querySelector<HTMLInputElement>("input");if(!input||input.disabled){event.preventDefault();event.stopImmediatePropagation();return;}input.checked=!input.checked;option.classList.toggle("selected",!!input.checked);event.preventDefault();event.stopImmediatePropagation();syncRuleConflicts();summary();return;}if(target.closest("[data-nuz-start]")){event.preventDefault();event.stopImmediatePropagation();game.nuzlockeRules=selectedRules();game.nuzlockeActive=true;game.nuzlockeGraveyard=[];game.nuzlockeRecruitCount=0;game.nuzlockeFirstPickId=null;overlay?.remove();game.start();}},true);
}
