import { Game } from "../game/Game";
import type { Developer, MapNode } from "../entities/types";

const root = document.querySelector<HTMLDivElement>("#app")!;
function pct(value: number, max: number) { return max <= 0 ? 0 : Math.max(0, Math.min(100, Math.round((value / max) * 100))); }
function esc(value: string) { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }

function equipmentSlots(dev: Developer) {
  return `<div class="equipment-slots"><strong>EQUIPAGGIAMENTO</strong><div class="slot-row">${[0,1].map(i => dev.items[i] ? `<div class="equip-slot filled"><span>SLOT ${i+1}</span><b>${esc(dev.items[i].name)}</b><small>+${dev.items[i].codeBonus} COD · +${dev.items[i].debugBonus} DEBUG</small></div>` : `<div class="equip-slot empty"><span>SLOT ${i+1}</span><b>VUOTO</b><small>Disponibile</small></div>`).join("")}</div></div>`;
}
function devCard(dev: Developer, selected=false, compact=false) {
  return `<div class="dev-card ${selected ? "selected" : ""} ${compact ? "compact" : ""}"><div class="dev-head"><b>${esc(dev.name)}</b><span>${esc(dev.role)}</span></div><p class="dev-description">${esc(dev.description)}</p><div class="stat-line"><span>HP</span><b>${dev.hp}/${dev.maxHp}</b></div><div class="bar"><i style="width:${pct(dev.hp,dev.maxHp)}%"></i></div><div class="stat-line"><span>STRESS</span><b>${dev.stress}/100</b></div><div class="stress"><i style="width:${dev.stress}%"></i></div><div class="stat-grid"><span>CODICE <b>${dev.code}</b></span><span>DEBUG <b>${dev.debug}</b></span></div><div class="ability"><strong>ABILITÀ</strong><br>${esc(dev.passive)}</div><div class="matchup-grid"><div><strong>VANTAGGI</strong>${dev.advantages.map(x=>`<span>+ ${esc(x)}</span>`).join("")}</div><div><strong>DEBOLEZZE</strong>${dev.weaknesses.map(x=>`<span>− ${esc(x)}</span>`).join("")}</div></div>${equipmentSlots(dev)}</div>`;
}
function enemyCard(enemy: import("../entities/types").Enemy) {
  return `<div class="enemy-team-card"><div class="enemy-head"><div><div class="enemy-type">${esc(enemy.type)}</div><div class="enemy-name">${esc(enemy.name)}</div></div><span class="enemy-badge">NEMICO</span></div><p class="enemy-description">${esc(enemy.description)}</p><div class="big-hp">${enemy.hp}/${enemy.maxHp} HP</div><div class="bar"><i style="width:${pct(enemy.hp,enemy.maxHp)}%"></i></div><div class="enemy-stat-grid"><span>CODICE <b>${enemy.code}</b></span><span>DEBUG <b>${enemy.debug}</b></span><span>DMG <b>${enemy.intent.damage}</b></span><span>STRESS <b>+${enemy.intent.stress}</b></span></div><div class="enemy-ability"><strong>ABILITÀ</strong><br>${esc(enemy.passive)}</div><div class="matchup-grid enemy-matchup"><div><strong>VANTAGGI</strong>${enemy.advantages.map(x=>`<span>+ ${esc(x)}</span>`).join("")}</div><div><strong>DEBOLEZZE</strong>${enemy.weaknesses.map(x=>`<span>− ${esc(x)}</span>`).join("")}</div></div></div>`;
}
const nodeIcon: Record<MapNode["type"], string> = { battle:"⚔", elite:"☠", event:"?", rest:"+", fullRest:"♥", reward:"◆", item:"🔧", recruit:"👤", boss:"☠" };
function nodeClass(node: MapNode, game: Game) { const available=game.availableMapNodes.some(c=>c.id===node.id), current=game.currentMapNodeId===node.id; return ["map-node",`type-${node.type}`,node.visited?"visited":"",available?"available":"",current?"current":"",node.hiddenEncounter?"hidden-encounter":""].filter(Boolean).join(" "); }
function renderMapNode(node: MapNode, game: Game) { const available=game.availableMapNodes.some(c=>c.id===node.id); const hidden=node.hiddenEncounter&&(node.type==="battle"||node.type==="elite"); const label=hidden?"?":node.title; const typeLabel=hidden?"INCONTRO":node.type==="boss"?"BOSS":node.type.toUpperCase(); return `<button type="button" class="${nodeClass(node,game)}" data-map-node="${node.id}" ${available?"":"disabled"} title="${esc(node.description)}"><span class="node-icon">${nodeIcon[node.type]}</span><b>${esc(label)}</b><small>${typeLabel}</small></button>`; }
function renderMap(game: Game) {
  const width=900,rowHeight=100,x=(col:number)=>150+col*300,y=(row:number)=>55+row*rowHeight;
  const lines=game.mapNodes.flatMap(node=>node.next.map(nextId=>{const target=game.mapNodes.find(c=>c.id===nextId);if(!target)return "";const active=node.visited&&(target.visited||game.availableMapNodes.some(c=>c.id===target.id));return `<line class="map-line ${active?"active":""}" x1="${x(node.col)}" y1="${y(node.row)}" x2="${x(target.col)}" y2="${y(target.row)}"/>`;})).join("");
  const nodes=game.mapNodes.map(node=>`<div class="map-node-wrap" style="left:${x(node.col)/width*100}%;top:${y(node.row)}px">${renderMapNode(node,game)}</div>`).join("");
  return `<div class="map-viewport"><div class="map-canvas" style="height:${7*rowHeight+120}px"><svg class="map-lines" viewBox="0 0 900 ${7*rowHeight+120}" preserveAspectRatio="none">${lines}</svg>${nodes}</div></div>`;
}
function teamSummary(dev: Developer,i:number) { return `<div class="team-summary ${i===0?"main-member":""}">${devCard(dev,i===0,true)}</div>`; }

function battleSetup(game: Game) {
  const enemy=game.pendingEnemy!;
  return `<section class="panel battle-setup"><div class="selection-heading"><div><h2>SCHIERAMENTO</h2><p>Scegli il Developer da mandare in campo. Puoi cliccarlo oppure trascinarlo nello slot centrale.</p></div><span class="random-badge">PRIMO TURNO</span></div><div class="lineup"><div class="lineup-side team-lineup"><h3>IL TUO TEAM</h3><div class="setup-team">${game.team.map((dev,i)=>`<div class="draggable-dev ${game.selectedBattleStarterIndex===i?"selected":""} ${dev.hp<=0||dev.stress>=100?"disabled-dev":""}" draggable="${dev.hp>0&&dev.stress<100?"true":"false"}" data-battle-dev="${i}"><div class="setup-dev-card"><div class="setup-dev-inner">${devCard(dev,i===game.selectedBattleStarterIndex,true)}</div></div></div>`).join("")}</div></div><div class="battle-drop-zone" data-battle-drop><div class="drop-label">TRASCINA QUI</div><div class="drop-icon">VS</div><div class="drop-selected">${esc(game.team[game.selectedBattleStarterIndex]?.name??"NESSUNO")}</div><small>Questo Developer inizierà il combattimento</small></div><div class="lineup-side enemy-lineup"><h3>NEMICO</h3>${enemyCard(enemy)}</div></div><div class="setup-footer"><span>Clicca un Developer oppure trascinalo al centro.</span><button type="button" class="primary" data-action="confirm-battle">INIZIA COMBATTIMENTO</button></div></section>`;
}

function equipmentDeveloper(game: Game, dev: Developer, devIndex: number) {
  return `<div class="equipment-developer"><div class="equipment-dev-info">${devCard(dev,false,true)}</div><div class="equipment-move-slots"><h3>OGGETTI EQUIPAGGIATI</h3>${[0,1].map(i=>{const item=dev.items[i];const selected=game.equipmentSource?.zone==="dev"&&game.equipmentSource.devIndex===devIndex&&game.equipmentSource.itemIndex===i;return `<button type="button" class="move-slot ${item?"filled":"empty"} ${selected?"selected":""}" data-eq-source-zone="dev" data-eq-source-dev="${devIndex}" data-eq-source-item="${i}" ${item?"":"disabled"}><span>SLOT ${i+1}</span><b>${item?esc(item.name):"VUOTO"}</b><small>${item?`+${item.codeBonus} COD · +${item.debugBonus} DEBUG`:`Slot disponibile`}</small></button>`;}).join("")}</div></div>`;
}

function equipmentScreen(game: Game) {
  const team=game.equipmentTeam;
  const source=game.equipmentSource;
  return `<section class="panel equipment-panel"><div class="selection-heading"><div><h2>EQUIPMENT & ZAINO</h2><p>Seleziona un oggetto e poi clicca lo slot di destinazione. Puoi spostare e scambiare gli oggetti tra tutti i developer in qualsiasi momento.</p></div><span class="random-badge">ZAINO · ${game.inventory.length}</span></div><div class="equipment-layout"><div class="equipment-team"><h3>TEAM</h3>${team.map((dev,i)=>equipmentDeveloper(game,dev,i)).join("")}</div><aside class="backpack panel"><h3>ZAINO</h3><p>Oggetti non equipaggiati e oggetti extra.</p><div class="backpack-items">${game.inventory.length?game.inventory.map((item,i)=>{const selected=source?.zone==="bag"&&source.itemIndex===i;return `<button type="button" class="backpack-item ${selected?"selected":""}" data-eq-source-zone="bag" data-eq-source-item="${i}"><b>${esc(item.name)}</b><span>+${item.codeBonus} COD · +${item.debugBonus} DEBUG</span><small>${esc(item.description)}</small></button>`;}).join(""):"<div class="backpack-empty">ZAINO VUOTO</div>"}</div><button type="button" class="bag-drop" data-eq-target-zone="bag" data-eq-target-item="-1">METTI NELLO ZAINO</button></aside></div><div class="equipment-footer"><span>${source?"Oggetto selezionato: scegli ora una destinazione.":"2 slot per developer. Gli oggetti extra restano nello zaino."}</span><button type="button" class="primary" data-action="close-equipment">TORNA INDIETRO</button></div></section>`;
}

export function render(game: Game) {
  root.innerHTML=`<main class="game-shell"><header><div><div class="logo">DEV<span>LIKE</span></div><small>SHIP IT OR BURN OUT.</small></div><div class="header-right"><div class="header-stat">MISSIONE ${game.projectNumber} · NODO ${game.currentNode}/7 · DIFFICOLTÀ x${game.difficulty.toFixed(1)}</div>${game.team.length&&game.screen!=="team"&&game.screen!=="result"?`<button type="button" class="equipment-button" data-action="open-equipment">EQUIPMENT · ZAINO ${game.inventory.length}</button>`:""}</div></header>${screen(game)}</main>`;
  bind(game);
}

function screen(game: Game) {
  if(game.screen==="menu")return `<section class="panel center"><div class="pixel-icon">⌨</div><h1>DEVLIKE</h1><p>Un roguelike dove il vero boss è il cliente.</p><button type="button" class="primary" data-action="start">NUOVO PROGETTO</button></section>`;
  if(game.screen==="team")return `<section class="panel selection-panel"><div class="selection-heading"><div><h2>SCEGLI IL DEVELOPER PRINCIPALE</h2><p>Ogni progetto parte con un solo developer. Gli altri arriveranno lungo il percorso.</p></div><span class="random-badge">3 CANDIDATI CASUALI</span></div><div class="developer-choice-grid">${game.startingCandidates.map((dev,i)=>`<button type="button" class="developer-choice ${game.selectedStartingId===dev.id?"selected":""}" data-dev="${dev.id}">${devCard(dev,game.selectedStartingId===dev.id)}</button>`).join("")}</div><div class="selection-footer"><div class="selection-hint">${game.selectedStartingId?"Developer selezionato. Controlla statistiche, abilità, vantaggi e debolezze, poi conferma.":"Clicca una scheda per selezionare il tuo protagonista."}</div><button type="button" class="primary" data-action="confirm-start" ${game.selectedStartingId?"":"disabled"}>INIZIA IL PROGETTO</button></div></section>`;
  if(game.screen==="map"){const choices=game.availableMapNodes;return `<section class="panel map-panel"><div class="map-top"><div><b>MISSIONE #${game.projectNumber}</b><br><small>${esc(game.message||"Scegli il prossimo nodo.")}</small></div><div class="map-progress">DIFFICOLTÀ x${game.difficulty.toFixed(1)}<br><b>${"█".repeat(Math.max(0,game.currentNode))+"░".repeat(Math.max(0,7-game.currentNode))}</b></div></div><div class="roguelike-help"><span>● ATTUALE</span><span>⚔ COMBATTIMENTO</span><span>☠ ELITE</span><span>◆ TOOL</span><span>🔧 OGGETTO</span><span>👤 RECLUTA</span><span>+ PAUSA</span><span>♥ CURA TOTALE</span><span>? IGNOTO/EVENTO</span><span>☠ DEADLINE</span></div>${renderMap(game)}<div class="choice-panel"><b>${choices.length?`SCEGLI IL PROSSIMO NODO · ${choices.length} STRADE`:"PERCORSO CONCLUSO"}</b><small>${choices.length?choices.map(node=>`${nodeIcon[node.type]} ${node.hiddenEncounter?"?":node.title} — ${node.description}`).join("<br>"):"La Deadline è vicina."}</small></div><div class="team-strip">${game.team.map(teamSummary).join("")}</div></section>`;}
  if(game.screen==="battleSetup")return battleSetup(game);
  if(game.screen==="recruit")return `<section class="panel selection-panel"><div class="selection-heading"><div><h2>RECLUTAMENTO</h2><p>${esc(game.message)}</p></div><span class="random-badge">3 CANDIDATI</span></div><div class="developer-choice-grid">${game.recruitCandidates.map((dev,i)=>`<button type="button" class="developer-choice" data-recruit-index="${i}">${devCard(dev,game.selectedRecruitIndex===i)}</button>`).join("")}</div>${game.team.length>=3?`<div class="replacement-box"><h3>SOSTITUISCI UN MEMBRO</h3><p>Hai già 3 developer. Seleziona prima il membro da mandare via.</p><div class="replacement-team">${game.team.map((dev,i)=>`<button type="button" class="replace-target ${game.recruitTargetIndex===i?"selected":""}" data-target="${i}">${dev.name}<small>${dev.role} · HP ${dev.hp} · Oggetti ${dev.items.length}/2</small></button>`).join("")}</div><button type="button" class="primary" data-action="confirm-recruit" ${game.selectedRecruitIndex!==null&&game.recruitTargetIndex!==null?"":"disabled"}>SOSTITUISCI MEMBRO</button></div>`:`<p class="recruit-note">Scegli un candidato: entrerà immediatamente nel team.</p>`}</section>`;
  if(game.screen==="itemReward"&&game.itemReward)return `<section class="panel selection-panel"><div class="selection-heading"><div><h2>OGGETTO SBLOCCATO</h2><p>${esc(game.message)}</p></div><span class="random-badge">EQUIPAGGIAMENTO</span></div><div class="item-reward-card"><h2>${esc(game.itemReward.name)}</h2><p>${esc(game.itemReward.description)}</p><div class="item-bonus">+${game.itemReward.codeBonus} CODICE · +${game.itemReward.debugBonus} DEBUG</div></div><h3 class="assign-title">A QUALE DEVELOPER CONSEGNARLO?</h3><div class="assignment-grid">${game.team.map((dev,i)=>`<button type="button" class="assignment-card ${game.selectedItemTargetIndex===i?"selected":""}" data-item-target="${i}" ${dev.items.length>=2?"disabled":""}><div><b>${esc(dev.name)}</b><span>${esc(dev.role)}</span></div><div class="item-target-stats">HP ${dev.hp}/${dev.maxHp} · COD ${dev.code} · DEBUG ${dev.debug}</div><div class="matchup-mini"><strong>VANTAGGI</strong> ${dev.advantages.join(" · ")}<br><strong>DEBOLEZZE</strong> ${dev.weaknesses.join(" · ")}</div><div>${equipmentSlots(dev)}</div><em>${dev.items.length>=2?"INVENTARIO PIENO — USA LO ZAINO":"CLICCA PER SELEZIONARE"}</em></button>`).join("")}</div><div class="selection-footer"><div class="selection-hint">${game.selectedItemTargetIndex===null?"Puoi anche metterlo direttamente nello zaino.":`Consegnerai ${esc(game.itemReward.name)} a ${esc(game.team[game.selectedItemTargetIndex]?.name??"")}.`}</div><div class="reward-actions"><button type="button" class="secondary" data-action="store-item">METTI NELLO ZAINO</button><button type="button" class="primary" data-action="confirm-item" ${game.selectedItemTargetIndex!==null?"":"disabled"}>EQUIPAGGIA OGGETTO</button></div></div></section>`;
  if(game.screen==="equipment")return equipmentScreen(game);
  if(game.screen==="combat"&&game.combat){const c=game.combat;return `<section class="battle"><div class="enemy panel">${enemyCard(c.enemy)}<div class="intent">INTENT: ${esc(c.enemy.intent.label)} · ${c.enemy.intent.damage} DMG · +${c.enemy.intent.stress} STRESS</div></div><div class="combat-area"><div class="active-dev panel"><div class="combat-active-heading"><h3>DEVELOPER ATTIVO</h3><span>TURNO ${c.turn}</span></div>${devCard(c.active,true)}<div class="energy">ENERGIA: ${"⚡".repeat(c.energy)}${"·".repeat(3-c.energy)}</div><div class="combat-actions"><button type="button" data-action="code">CODA<br><small>1 ⚡</small></button><button type="button" data-action="debug">DEBUG<br><small>2 ⚡</small></button><button type="button" data-action="defend">DIFESA<br><small>1 ⚡</small></button></div><div class="hand">${c.hand.map((card,i)=>`<button type="button" class="card" data-card="${i}" ${card.cost>c.energy?"disabled":""}><b>${esc(card.name)}</b><span>${card.cost} ⚡</span><small>${esc(card.description)}</small></button>`).join("")}</div><button type="button" class="end" data-action="end-turn">FINE TURNO</button></div><aside class="bench panel"><h3>PANCHINA</h3>${c.team.map((d,i)=>`<button type="button" class="bench-dev ${i===c.activeIndex?"active":""}" data-switch="${i}" ${i===c.activeIndex||d.hp<=0||d.stress>=100?"disabled":""}>${d.name} · HP ${d.hp}/${d.maxHp} · S ${d.stress} · O ${d.items.length}/2</button>`).join("")}<h3>LOG</h3><div class="log">${c.log.slice(-8).reverse().map(x=>`<div>${esc(x)}</div>`).join("")}</div></aside></div></section>`;}
  if(game.screen==="reward"){const card=game.reward!;return `<section class="panel center"><h2>RICOMPENSA</h2><p>Il percorso continua. Aggiungi un Tool al deck.</p><button type="button" class="reward-card" data-action="reward"><b>${esc(card.name)}</b><span>${card.cost} ⚡</span><small>${esc(card.description)}</small></button></section>`;}
  return `<section class="panel center result"><div class="pixel-icon">☠</div><h1>${esc(game.message)}</h1><p>Il progetto è andato in produzione. Da qualche parte.</p><button type="button" class="primary" data-action="restart">NUOVO PROGETTO</button></section>`;
}

function bind(game: Game) {
  root.querySelectorAll<HTMLElement>("[data-action]").forEach(el=>el.onclick=()=>{const action=el.dataset.action;if(action==="start")game.start();if(action==="confirm-start")game.confirmStartingDeveloper();if(action==="confirm-battle")game.confirmBattleStarter();if(action==="code")game.combat?.basicAction("code");if(action==="debug")game.combat?.basicAction("debug");if(action==="defend")game.combat?.basicAction("defend");if(action==="end-turn")game.combat?.endTurn();if(action==="reward")game.chooseReward(0);if(action==="confirm-recruit")game.confirmRecruitment();if(action==="confirm-item")game.confirmItemReward();if(action==="store-item")game.storeItemReward();if(action==="open-equipment")game.openEquipment();if(action==="close-equipment")game.closeEquipment();if(action==="restart")game.restart();render(game);if(game.screen==="combat"&&game.combat?.result!=="ongoing"){game.onCombatFinished();render(game);}});
  root.querySelectorAll<HTMLElement>("[data-dev]").forEach(el=>el.onclick=e=>{e.preventDefault();if(game.screen==="team"){const index=game.startingCandidates.findIndex(dev=>dev.id===el.dataset.dev);if(index>=0)game.selectStartingDeveloper(index);}render(game);});
  root.querySelectorAll<HTMLElement>("[data-card]").forEach(el=>el.onclick=()=>{game.combat?.playCard(Number(el.dataset.card));render(game);if(game.combat?.result!=="ongoing"){game.onCombatFinished();render(game);}});
  root.querySelectorAll<HTMLElement>("[data-switch]").forEach(el=>el.onclick=()=>{game.combat?.switchDeveloper(Number(el.dataset.switch));render(game);});
  root.querySelectorAll<HTMLElement>("[data-map-node]").forEach(el=>el.onclick=()=>{game.selectMapNode(el.dataset.mapNode!);render(game);});
  root.querySelectorAll<HTMLElement>("[data-target]").forEach(el=>el.onclick=()=>{game.selectRecruitTarget(Number(el.dataset.target));render(game);});
  root.querySelectorAll<HTMLElement>("[data-item-target]").forEach(el=>el.onclick=()=>{game.selectItemTarget(Number(el.dataset.itemTarget));render(game);});
  root.querySelectorAll<HTMLElement>("[data-recruit-index]").forEach(el=>el.onclick=e=>{e.preventDefault();game.selectRecruitCandidate(Number(el.dataset.recruitIndex));render(game);});
  root.querySelectorAll<HTMLElement>("[data-eq-source-zone]").forEach(el=>el.onclick=()=>{game.selectEquipmentSource(el.dataset.eqSourceZone as "dev"|"bag",Number(el.dataset.eqSourceItem),Number(el.dataset.eqSourceDev??-1));render(game);});
  root.querySelectorAll<HTMLElement>("[data-eq-target-zone]").forEach(el=>el.onclick=()=>{game.moveSelectedEquipment(el.dataset.eqTargetZone as "dev"|"bag",Number(el.dataset.eqTargetDev??-1),Number(el.dataset.eqTargetItem??-1));render(game);});
  if(game.screen==="battleSetup"){
    let draggedIndex:number|null=null;
    root.querySelectorAll<HTMLElement>("[data-battle-dev]").forEach(el=>{const index=Number(el.dataset.index ?? el.dataset.battleDev);el.onclick=e=>{e.preventDefault();game.selectBattleStarter(index);render(game);};el.ondragstart=e=>{draggedIndex=index;e.dataTransfer?.setData("text/plain",String(index));if(e.dataTransfer)e.dataTransfer.effectAllowed="move";el.classList.add("dragging");};el.ondragend=()=>{draggedIndex=null;el.classList.remove("dragging");};});
    const drop=root.querySelector<HTMLElement>("[data-battle-drop]");
    if(drop){drop.ondragover=e=>{e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect="move";drop.classList.add("drag-over");};drop.ondragleave=()=>drop.classList.remove("drag-over");drop.ondrop=e=>{e.preventDefault();drop.classList.remove("drag-over");const raw=e.dataTransfer?.getData("text/plain");const parsed=raw?Number(raw):NaN;const index=Number.isInteger(parsed)?parsed:draggedIndex;if(index!==null&&Number.isInteger(index))game.moveBattleStarter(index);render(game);};}
  }
}
