import { rewardCards, rewardCardTiers, startingDeck } from "./data/cards";
import type { Card } from "./entities/types";

type CardGame = { deck?: Card[]; cardCollection?: Card[] };
const esc = (value:string) => value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const cards = new Map<string,Card>([...startingDeck,...rewardCards].map(card=>[card.id,card]));
const art:Record<string,string>={git:">_",coffee:"☕",docker:"◈","stack-overflow":"∞","ctrl-z":"↶",grep:"?",terminal:"$_",lint:"✓",wireframe:"⌗","quick-fix":"⚡",script:"{}",monitor:"▣",cache:"◆","api-call":"⇄",prototype:"◇",exploit:"☠","freelance-hustle":"$",chatgpt:"AI",jira:"J",google:"G","rubber-duck":"◉","stackoverflow-copy":"∞","npm-install":"N","git-pull":"↓","console-log":">_",breakpoint:"⌁","rubber-duck-debug":"?","unit-test":"✓",sleep:"Z",documentation:"≡","rubber-stamp":"OK","git-push":"↑","merge-conflict":"×",regex:".*",refactor:"↻","legacy-patch":"!","stackoverflow-answer":"∞","integration-test":"⇄",hotfix:"⚡",rollback:"↩","meeting-cancel":"×","energy-drink-card":"⚡","ai-slop":"AI","coffee-overdose":"☕",production:"⚙","code-review":"✓","deadline-extension":"+","chatgpt-protocol":"AI","emergency-hotfix":"⚡"};

function effectText(card:Card){const effect=card.effect as Card["effect"]&{amount?:number};const amount=effect.amount;switch(effect.type){case "damage":return amount===undefined?"DANNO":`DANNO · ${amount}`;case "heal":return amount===undefined?"CURA":`CURA · ${amount} HP`;case "block":return amount===undefined?"DIFESA":`DIFESA · ${amount}`;case "removeStress":return amount===undefined?"RIDUCE STRESS":`STRESS · -${amount}`;case "codeBoost":return amount===undefined?"BOOST DANNI":`BOOST · +${amount}% DANNI`;default:return String(effect.type).toUpperCase();}}
export function cardById(id:string){const base=cards.get(id);return base?{...base,tier:base.tier??rewardCardTiers[id]??1}:undefined;}
export function renderPokerCard(card:Card){const tier=card.tier??rewardCardTiers[card.id]??1;return `<div class="devlike-poker-card devlike-poker-card-tier-${tier}"><div class="devlike-poker-inner"><div class="devlike-poker-top"><span class="devlike-poker-cost">${card.cost}<b>⚡</b></span><span class="devlike-poker-tier">T${tier}</span></div><div class="devlike-poker-name">${esc(card.name)}</div><div class="devlike-poker-art"><span>${esc(art[card.id]??"✦")}</span></div><div class="devlike-poker-type">TOOL</div><div class="devlike-poker-effect"><b>${esc(effectText(card))}</b><p>${esc(card.description)}</p></div></div></div>`;}
function game():CardGame|undefined{return (window as Window&{__devlikeGame?:CardGame}).__devlikeGame;}
function transformPlayable(element:HTMLElement){if(element.dataset.pokerRendered==="true")return;const id=element.dataset.card;if(!id)return;const card=cardById(id);if(!card)return;element.dataset.pokerRendered="true";element.classList.add("devlike-poker-host");element.innerHTML=renderPokerCard(card);}
function transformDeck(element:HTMLElement){if(element.dataset.pokerRendered==="true")return;const g=game();if(!g)return;const action=element.querySelector<HTMLElement>("[data-deck-action]");if(!action)return;const index=Number(action.dataset.deckIndex);const isRemove=action.dataset.deckAction==="remove";const source=isRemove?g.deck:g.cardCollection;const card=source?.[index];if(!card)return;const actionMarkup=action.outerHTML;const meta=isRemove?`NEL MAZZO · ${g.deck?.length??0}`:`POSSEDUTE · ${g.cardCollection?.filter(item=>item.id===card.id).length??0} · MAZZO · ${g.deck?.filter(item=>item.id===card.id).length??0}`;element.dataset.pokerRendered="true";element.classList.add("devlike-poker-management-host");element.innerHTML=`${renderPokerCard({...card,tier:card.tier??rewardCardTiers[card.id]??1})}<div class="devlike-poker-management"><span>${meta}</span>${actionMarkup}</div>`;}
function transformAll(){document.querySelectorAll<HTMLElement>("[data-card]").forEach(transformPlayable);document.querySelectorAll<HTMLElement>(".deck-card").forEach(transformDeck);}
export function setupCardView(){transformAll();const observer=new MutationObserver(transformAll);observer.observe(document.querySelector("#app")??document.body,{childList:true,subtree:true});}
